name: dbt CI Run on Pull Request to Main 

on: 
  pull_request:
    branches: 
      - main

jobs:
  run_dbt_on_pull_request_to_main:
    name: dbt CI Run on Pull Request to Main
    runs-on: ubuntu-latest

    env:
      DBT_API_KEY:             ${{ secrets.DBT_API_KEY }}
      DBT_URL:                 https://cloud.getdbt.com # no trailing backslash. Change this for single tenant deployments to your actual base url
      DBT_JOB_CAUSE:           'Continuous Integration Check (Slim CI)' # provide a descriptive job cause here for easy debugging down the road
      DBT_ACCOUNT_ID:          66543
      DBT_PROJECT_ID:          106453 
      DBT_PR_JOB_ID:           158634 
      # DBT_JOB_BRANCH:           
      # DBT_JOB_SCHEMA_OVERRIDE: 

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Trigger dbt job
      run: |
        python -u ./python/run_and_monitor_dbt_cloud_job.py